import React, { useState } from 'react';
import { 
  Settings, 
  Save, 
  FileText, 
  Check, 
  RotateCw, 
  AlertCircle,
  HelpCircle,
  Sliders,
  ShieldAlert
} from 'lucide-react';
import { MinecraftServer, ServerProperties } from '../types';

interface ServerPropertiesTabProps {
  server: MinecraftServer;
  onSaveProperties: (properties: ServerProperties) => void;
}

export const ServerPropertiesTab: React.FC<ServerPropertiesTabProps> = ({
  server,
  onSaveProperties,
}) => {
  const [props, setProps] = useState<ServerProperties>({ ...server.properties });
  const [viewMode, setViewMode] = useState<'gui' | 'raw'>('gui');
  const [savedSuccess, setSavedSuccess] = useState(false);
  const [rawText, setRawText] = useState(formatRawProperties(server.properties));

  function formatRawProperties(p: ServerProperties): string {
    return `# Minecraft server properties
# Auto-generated by HyperSurge Minecraft Cloud
motd=${p.motd}
server-port=25565
max-players=${p['max-players']}
difficulty=${p.difficulty}
gamemode=${p.gamemode}
pvp=${p.pvp}
online-mode=${p['online-mode']}
white-list=${p['white-list']}
view-distance=${p['view-distance']}
simulation-distance=${p['simulation-distance']}
spawn-protection=${p['spawn-protection']}
allow-nether=${p['allow-nether']}
enable-command-block=${p['enable-command-block']}
hardcore=${p.hardcore}
allow-flight=${p['allow-flight']}
level-seed=${p['level-seed']}
enable-status=true
enable-rcon=false
network-compression-threshold=256
`;
  }

  const handleSave = () => {
    if (viewMode === 'raw') {
      // Parse raw text back into properties
      const lines = rawText.split('\n');
      const updated = { ...props };
      lines.forEach(line => {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) return;
        const [key, ...valParts] = trimmed.split('=');
        const val = valParts.join('=').trim();
        if (key && val !== undefined) {
          if (key === 'motd') updated.motd = val;
          if (key === 'max-players') updated['max-players'] = parseInt(val) || 20;
          if (key === 'difficulty') updated.difficulty = val as any;
          if (key === 'gamemode') updated.gamemode = val as any;
          if (key === 'pvp') updated.pvp = val === 'true';
          if (key === 'online-mode') updated['online-mode'] = val === 'true';
          if (key === 'white-list') updated['white-list'] = val === 'true';
          if (key === 'view-distance') updated['view-distance'] = parseInt(val) || 10;
          if (key === 'simulation-distance') updated['simulation-distance'] = parseInt(val) || 8;
          if (key === 'spawn-protection') updated['spawn-protection'] = parseInt(val) || 16;
          if (key === 'allow-nether') updated['allow-nether'] = val === 'true';
          if (key === 'enable-command-block') updated['enable-command-block'] = val === 'true';
          if (key === 'hardcore') updated.hardcore = val === 'true';
          if (key === 'allow-flight') updated['allow-flight'] = val === 'true';
          if (key === 'level-seed') updated['level-seed'] = val;
        }
      });
      setProps(updated);
      onSaveProperties(updated);
    } else {
      onSaveProperties(props);
      setRawText(formatRawProperties(props));
    }

    setSavedSuccess(true);
    setTimeout(() => setSavedSuccess(false), 2500);
  };

  return (
    <div className="space-y-6">
      {/* Header bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 rounded-2xl bg-slate-900 border border-slate-800">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
            <Settings className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-white">Server Configuration (server.properties)</h2>
            <p className="text-xs text-slate-400">Tune gameplay settings, player limits, and rendering distances</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {/* Mode switch */}
          <div className="flex items-center p-1 rounded-xl bg-slate-950 border border-slate-800 text-xs">
            <button
              onClick={() => {
                setRawText(formatRawProperties(props));
                setViewMode('gui');
              }}
              className={`px-3 py-1.5 rounded-lg font-medium transition-colors ${
                viewMode === 'gui' ? 'bg-slate-800 text-emerald-400 shadow-sm' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Visual Editor
            </button>
            <button
              onClick={() => {
                setRawText(formatRawProperties(props));
                setViewMode('raw');
              }}
              className={`px-3 py-1.5 rounded-lg font-medium transition-colors ${
                viewMode === 'raw' ? 'bg-slate-800 text-emerald-400 shadow-sm' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Raw File (server.properties)
            </button>
          </div>

          <button
            id="save-properties-btn"
            onClick={handleSave}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-bold transition-all shadow-md shadow-emerald-500/20 active:scale-95"
          >
            {savedSuccess ? (
              <>
                <Check className="w-4 h-4 stroke-[3]" />
                <span>Saved &amp; Updated</span>
              </>
            ) : (
              <>
                <Save className="w-4 h-4" />
                <span>Save Properties</span>
              </>
            )}
          </button>
        </div>
      </div>

      {savedSuccess && (
        <div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-xs flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Check className="w-4 h-4" />
            <span>Changes saved to <strong>server.properties</strong>. Note: Some settings take effect on next server restart.</span>
          </div>
        </div>
      )}

      {viewMode === 'gui' ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* General Gameplay Settings */}
          <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800 space-y-4">
            <div className="text-xs font-bold text-white uppercase tracking-wider flex items-center gap-2">
              <Sliders className="w-4 h-4 text-emerald-400" />
              <span>Gameplay &amp; Difficulty</span>
            </div>

            <div className="space-y-3">
              <div>
                <label className="block text-xs font-medium text-slate-300 mb-1">Server MOTD (Message of the Day)</label>
                <input
                  type="text"
                  value={props.motd}
                  onChange={(e) => setProps({ ...props, motd: e.target.value })}
                  className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-white text-xs font-mono focus:border-emerald-500 focus:outline-none"
                  placeholder="§aWelcome to our Minecraft Server!"
                />
                <span className="text-[10px] text-slate-500 block mt-1">
                  Supports Minecraft color codes: §a (green), §b (aqua), §c (red), §e (yellow), §6 (gold), §l (bold).
                </span>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium text-slate-300 mb-1">Difficulty</label>
                  <select
                    value={props.difficulty}
                    onChange={(e) => setProps({ ...props, difficulty: e.target.value as any })}
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-white text-xs focus:border-emerald-500 focus:outline-none"
                  >
                    <option value="peaceful">Peaceful</option>
                    <option value="easy">Easy</option>
                    <option value="normal">Normal</option>
                    <option value="hard">Hard</option>
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-medium text-slate-300 mb-1">Default Gamemode</label>
                  <select
                    value={props.gamemode}
                    onChange={(e) => setProps({ ...props, gamemode: e.target.value as any })}
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-white text-xs focus:border-emerald-500 focus:outline-none"
                  >
                    <option value="survival">Survival</option>
                    <option value="creative">Creative</option>
                    <option value="adventure">Adventure</option>
                    <option value="spectator">Spectator</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-300 mb-1">World Generation Seed</label>
                <input
                  type="text"
                  value={props['level-seed']}
                  onChange={(e) => setProps({ ...props, 'level-seed': e.target.value })}
                  className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-white text-xs font-mono focus:border-emerald-500 focus:outline-none"
                  placeholder="Random if empty"
                />
              </div>

              <div className="grid grid-cols-2 gap-3 pt-2">
                <label className="flex items-center gap-2 cursor-pointer p-2.5 rounded-xl bg-slate-950 border border-slate-800">
                  <input
                    type="checkbox"
                    checked={props.pvp}
                    onChange={(e) => setProps({ ...props, pvp: e.target.checked })}
                    className="rounded accent-emerald-500"
                  />
                  <div>
                    <div className="text-xs font-semibold text-white">Enable PVP</div>
                    <div className="text-[10px] text-slate-400">Player versus player combat</div>
                  </div>
                </label>

                <label className="flex items-center gap-2 cursor-pointer p-2.5 rounded-xl bg-slate-950 border border-slate-800">
                  <input
                    type="checkbox"
                    checked={props.hardcore}
                    onChange={(e) => setProps({ ...props, hardcore: e.target.checked })}
                    className="rounded accent-emerald-500"
                  />
                  <div>
                    <div className="text-xs font-semibold text-white">Hardcore Mode</div>
                    <div className="text-[10px] text-slate-400">One life, then banned/spectator</div>
                  </div>
                </label>
              </div>
            </div>
          </div>

          {/* Multiplayer & Limits */}
          <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800 space-y-4">
            <div className="text-xs font-bold text-white uppercase tracking-wider flex items-center gap-2">
              <Settings className="w-4 h-4 text-emerald-400" />
              <span>Multiplayer &amp; Networking</span>
            </div>

            <div className="space-y-3">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium text-slate-300 mb-1">Max Player Slots</label>
                  <input
                    type="number"
                    min={1}
                    max={500}
                    value={props['max-players']}
                    onChange={(e) => setProps({ ...props, 'max-players': parseInt(e.target.value) || 20 })}
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-white text-xs font-mono focus:border-emerald-500 focus:outline-none"
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-slate-300 mb-1">Spawn Protection</label>
                  <input
                    type="number"
                    min={0}
                    max={100}
                    value={props['spawn-protection']}
                    onChange={(e) => setProps({ ...props, 'spawn-protection': parseInt(e.target.value) || 0 })}
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-white text-xs font-mono focus:border-emerald-500 focus:outline-none"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium text-slate-300 mb-1">View Distance (Chunks)</label>
                  <input
                    type="range"
                    min={4}
                    max={32}
                    value={props['view-distance']}
                    onChange={(e) => setProps({ ...props, 'view-distance': parseInt(e.target.value) })}
                    className="w-full accent-emerald-500"
                  />
                  <div className="flex justify-between text-[10px] text-slate-400 mt-1 font-mono">
                    <span>4 (Low)</span>
                    <span className="text-emerald-400 font-bold">{props['view-distance']} Chunks</span>
                    <span>32 (Max)</span>
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-medium text-slate-300 mb-1">Simulation Distance</label>
                  <input
                    type="range"
                    min={3}
                    max={16}
                    value={props['simulation-distance']}
                    onChange={(e) => setProps({ ...props, 'simulation-distance': parseInt(e.target.value) })}
                    className="w-full accent-emerald-500"
                  />
                  <div className="flex justify-between text-[10px] text-slate-400 mt-1 font-mono">
                    <span>3 (Fast)</span>
                    <span className="text-emerald-400 font-bold">{props['simulation-distance']} Chunks</span>
                    <span>16</span>
                  </div>
                </div>
              </div>

              <div className="space-y-2 pt-2">
                <label className="flex items-center gap-2 cursor-pointer p-2.5 rounded-xl bg-slate-950 border border-slate-800">
                  <input
                    type="checkbox"
                    checked={props['online-mode']}
                    onChange={(e) => setProps({ ...props, 'online-mode': e.target.checked })}
                    className="rounded accent-emerald-500"
                  />
                  <div>
                    <div className="text-xs font-semibold text-white">Online Mode (Mojang Authentication)</div>
                    <div className="text-[10px] text-slate-400">Verifies paid Minecraft accounts against Mojang session servers</div>
                  </div>
                </label>

                <label className="flex items-center gap-2 cursor-pointer p-2.5 rounded-xl bg-slate-950 border border-slate-800">
                  <input
                    type="checkbox"
                    checked={props['white-list']}
                    onChange={(e) => setProps({ ...props, 'white-list': e.target.checked })}
                    className="rounded accent-emerald-500"
                  />
                  <div>
                    <div className="text-xs font-semibold text-white">Enable Whitelist</div>
                    <div className="text-[10px] text-slate-400">Only players in whitelist.json can connect</div>
                  </div>
                </label>

                <label className="flex items-center gap-2 cursor-pointer p-2.5 rounded-xl bg-slate-950 border border-slate-800">
                  <input
                    type="checkbox"
                    checked={props['enable-command-block']}
                    onChange={(e) => setProps({ ...props, 'enable-command-block': e.target.checked })}
                    className="rounded accent-emerald-500"
                  />
                  <div>
                    <div className="text-xs font-semibold text-white">Enable Command Blocks</div>
                    <div className="text-[10px] text-slate-400">Allows in-game automation and custom maps</div>
                  </div>
                </label>
              </div>
            </div>
          </div>
        </div>
      ) : (
        /* RAW server.properties File View */
        <div className="space-y-2">
          <div className="text-xs text-slate-400 flex items-center justify-between">
            <span>Directly edit /home/container/server.properties</span>
            <span className="font-mono text-[11px] text-slate-500">UTF-8 Plain Text</span>
          </div>
          <textarea
            value={rawText}
            onChange={(e) => setRawText(e.target.value)}
            rows={18}
            className="w-full p-4 rounded-2xl bg-slate-950 border border-slate-800 font-mono text-xs text-emerald-300 focus:outline-none focus:border-emerald-500 leading-relaxed terminal-scroll"
            spellCheck={false}
          />
        </div>
      )}
    </div>
  );
};
